name: Python package
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: 'pip' # caching pip dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install dev dependencies
        run:  pip install -r requirements_test.txt
      - name: Run Linter
        run: flake8 formation_indus_ds_avancee
      - name: Run Vulture
        run: vulture formation_indus_ds_avancee scripts --min-confidence 100
      - name: Run tests
        run: python -m pytest --cov=formation_indus_ds_avancee/ tests/test_unit/ -vv -p no:warnings
      # Add behave command
      - name: Run behave
        run:  behave tests/test_functional/features

